### ISSUE TITLE
Upstreaming

### ISSUE THREAD

**Issue by quozl** [hyperyoda/netrek-client-brmh#3]
Development here has happened in a disassociated fork.

https://github.com/netrek/netrek-client-brmh is the official repository, please submit the changes upstream and then delete this repository and fork the main one.

**Comment by hyperyoda** [comment]
How exactly do I submit the changes upstream? I'm trying 'git push' but
getting fatal error.

root@hockey:/var/www/html/git# git push
https://github.com/netrek/netrek-client-brmh.git netrek-client-brmh/
fatal: not a git repository (or any of the parent directories): .git
root@hockey:/var/www/html/git# git push
https://github.com/netrek/netrek-client-brmh netrek-client-brmh/
fatal: not a git repository (or any of the parent directories): .git
root@hockey:/var/www/html/git# git push
https://github.com/netrek/netrek-client-brmh.git
fatal: not a git repository (or any of the parent directories): .git
root@hockey:/var/www/html/git#

Zach


<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by quozl** [comment]
Not for me to say how you use GitHub.  There are many ways to do it.  Please begin with [creating a pull request](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request).

Your reply is badly formatted.  I can't edit it down to remove the crap, because you used mail to reply.

**Comment by hyperyoda** [comment]
On Tue, Jun 30, 2020 at 6:01 PM James Cameron <notifications@github.com>
wrote:

> Not for me to say how you use GitHub. There are many ways to do it. Please
> begin with creating a pull request
> <https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request>
> .
>
> Your reply is badly formatted. I'll edit it down to remove the crap.
>

When I got to the "Comparing changes" part of the pull request it would not
let me select netrek/netrek-client-brmh. It listed bgloyer and quozl bases
that I could select. When I entered: netrek/netrek-client-brmh  It said
"Nothing to show".

Zach

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by hyperyoda** [comment]
On Tue, Jun 30, 2020 at 8:49 PM Zachary Uram <netrek@gmail.com> wrote:

> On Tue, Jun 30, 2020 at 6:01 PM James Cameron <notifications@github.com>
> wrote:
>
>> Not for me to say how you use GitHub. There are many ways to do it.
>> Please begin with creating a pull request
>> <https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request>
>> .
>>
>> Your reply is badly formatted. I'll edit it down to remove the crap.
>>
>
> When I got to the "Comparing changes" part of the pull request it would
> not let me select netrek/netrek-client-brmh. It listed bgloyer and quozl
> bases that I could select. When I entered: netrek/netrek-client-brmh  It
> said "Nothing to show".
>

That should say: It listed bgloyer and quozl head repositories.

Zach


<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by hyperyoda** [comment]
It says when I select quozl head repository:

There isn’t anything to compare.

hyperyoda:master is up to date with all commits from quozl:master.
Zach

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by quozl** [comment]
That is exactly my point and is why this issue was created.  The repositories in hyperyoda, bgloyer, and quozl are disassociated from the repository in netrek.  So the changes applied to these repositories have not been applied to the repository in netrek.

**Comment by quozl** [comment]
Your repository was from a tarball.  I'm not getting anywhere with this here, so I've posted to netrek-dev.
